dist: focal
sudo: true
language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
    - sudo apt-get install python-llvmlite

install:
    - pip install -r requirements.txt
    - pip uninstall -y shapely
    - pip install --no-binary shapely shapely

script:
    - python ./setup.py unittests
