dist: xenial
sudo: true
language: python
python:
    - "3.7"
    - "3.8"
before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libgfortran3 libblas-dev liblapack-dev
install:
    #- pip install git+https://github.com/SciTools/cartopy.git
    - pip install -r requirements.txt
    - pip uninstall -y shapely
    - pip install --no-binary shapely shapely
    - pip freeze
    - apt list --installed
script:
    - python ./setup.py unittests
