dist: xenial
sudo: true
language: python
python:
    - "3.7"
install: 
    - apt-get install proj-bin proj-data
    - apt-get install libgeos-dev libproj-dev
    - pip install -r requirements.txt
script:
    - python ./setup.py unittests
