dist: focal
sudo: true
language: python
python:
    - "3.7"
    - "3.8"
    - "3.9"

before_install:
    - sudo apt-get install libgeos-dev libproj-dev proj-data graphviz libblas-dev liblapack-dev
    - wget https://apt.llvm.org/llvm.sh
    - chmod +x llvm.sh
    - sudo ./llvm.sh 10
    - export LLVM_CONFIG=/usr/local/opt/llvm/bin/llvm-config

install:
    - pip install -r requirements.txt
    - pip uninstall -y shapely
    - pip install --no-binary shapely shapely

script:
    - python ./setup.py unittests
