image:
  - Visual Studio 2019
environment:
  matrix:
    - PYTHON: "C:\\Python39-x64"
      PYTHON_VERSION: "3.9.x"
      PYTHON_ARCH: "64"
init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%\\python -m pip install --upgrade pip"
  # for many packages
  - "%PYTHON%\\Scripts\\pip install pymyinstall numpy"
  # for numba
  - "%PYTHON%\\Scripts\\pip install importlib_metadata"
  - "%PYTHON%\\Scripts\\pymy_install3 cartopy pyproj shapely llvmlite numba"
  - "%PYTHON%\\Scripts\\pip install -r requirements.txt"

build: off

test_script:
  - "%PYTHON%\\python -u .\\setup.py unittests"

after_test:
  - "%PYTHON%\\python -u .\\setup.py bdist_wheel"

artifacts:
  - path: dist
    name: _check_python_install
