version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.0
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
                    sudo dpkg -i pandoc-2.2.1-1-amd64.deb
          
      - run:
          name: Install 7z, unrar
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      - run:
          name: Install pyproj (1)
          command: |
            echo "deb http://deb.debian.org/debian sid main" | sudo tee /etc/apt/sources.list.d/proj.list
            sudo apt-get -qq update
            sudo apt-get -t sid install -y libproj-dev proj-bin=6.2.1-1 proj-data libgeos-dev

      - run:
          name: Install pyproj (2)
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install git+https://github.com/pyproj4/pyproj.git

            # needed otherwise error: ImportError: libproj.so.9: cannot open shared object file: No such file or directory

      - run:
          name: Install pyproj (3)
          command: |
            wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj9_4.9.2-2_amd64.deb 
            sudo dpkg -i libproj9_4.9.2-2_amd64.deb 

      - run:
          name: Install cartopy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install scipy matplotlib cython shapely pyproj
            pip install git+https://github.com/SciTools/cartopy.git

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python ./setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python ./setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            python ./setup.py build_sphinx
            
      - run:
          name: copy documentation
          command: |
            mkdir -p test-reports/doc
            mkdir -p test-reports/pdf
            zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
            
      - store_artifacts:
          path: test-reports
          destination: test-reports