version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.8.2
    
    working_directory: ~/repo
    
    steps:
      - checkout

      - restore_cache:
          keys:
          - v2-dependencies-{{ checksum "requirements.txt" }}
          - v2-dependencies-

      - run:
          name: Install pandoc
          command: |
                    sudo apt-get update 
                    wget https://github.com/jgm/pandoc/releases/download/2.2.1/pandoc-2.2.1-1-amd64.deb
                    sudo dpkg -i pandoc-2.2.1-1-amd64.deb
          
      - run:
          name: Install 7z, unrar
          command: |
                    sudo apt-get install -y p7zip-full
          
      - run:
          name: Install InkScape
          command: |
                    sudo apt-get install -y inkscape
          
      - run:
          name: Install graphviz
          command: |
                    sudo apt-get install -y graphviz
          
      - run:
          name: Install libproj
          command: |
            # requires libstdc++6 >= 9
            sudo apt-get install -y libgeos-dev libproj-dev proj-data graphviz
            export PYPROJMAJVER=15
            export PYPROJVERSION=6.3.1-1
            # export PYPROJMAJVER=19
            #export PYPROJVERSION=7.0.1-1
            #wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj${PYPROJMAJVER}_${PYPROJVERSION}_amd64.deb
            #sudo dpkg -i libproj${PYPROJMAJVER}_${PYPROJVERSION}_amd64.deb
            #wget http://es.archive.ubuntu.com/ubuntu/pool/universe/p/proj/libproj-dev_${PYPROJVERSION}_amd64.deb
            #sudo dpkg -i libproj-dev_${PYPROJVERSION}_amd64.deb

      #- run:
      #    name: Install pyproj (2)
      #    command: |
      #      python3 -m venv venv
      #      . venv/bin/activate
      #      sudo pip install git+https://github.com/pyproj4/pyproj.git

      - run:
          name: Install standard libraries
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install scipy matplotlib numpy cython pandas

      - run:
          name: Install pyproj, shapely, cartopy
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install pyproj
            pip3 install --no-binary shapely shapely
            pip3 install cartopy

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v2-dependencies-{{ checksum "requirements.txt" }}
        
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip3 freeze
            apt list --installed
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python ./setup.py unittests

      - run:
          name: wheel
          command: |
            . venv/bin/activate
            python ./setup.py bdist_wheel
            mkdir -p test-reports/dist
            cp dist/*.whl test-reports/dist

      - run:
          name: documentation
          command: |
            . venv/bin/activate
            python3 ./setup.py build_sphinx
            
      - run:
          name: copy documentation
          command: |
            mkdir -p test-reports/doc
            mkdir -p test-reports/pdf
            zip -r -9  test-reports/doc/documentation_html.zip _doc/sphinxdoc/build/html
            
      - store_artifacts:
          path: test-reports
          destination: test-reports